#!/bin/bash

set -e
set -u

unset AWS_ACCESS_KEY
unset AWS_SECRET_KEY

for pkg in "$@"; do
    echo "*** Building $pkg"
    (cd "$pkg" && makepkg --syncdeps --rmdeps --skippgpcheck --nocheck --noconfirm && makepkg --install --noconfirm)
done
