#!/bin/bash

set -e
set -u

echo $PATH
which bash
echo $SHELL

for pkg in "$@"; do
    echo "*** Building $pkg"
    (cd "$pkg" && echo "$PATH" && makepkg --syncdeps --rmdeps --skippgpcheck --nocheck --noconfirm && makepkg --install --noconfirm)
done
