#!/bin/bash

set -e
set -u
set -o pipefail

target="${*:$#}"
files=("${@:1:$# - 1}")
name="catalina"
arch="x86_64"

mkdir -p "${target}"

if [ "${#files[@]}" -eq 0 ]; then
    exit
fi

for f in "${files[@]}"; do
    dst="${target}/${f%%/*}/${name}/${arch}"
    mkdir -p "${dst}"
    cp -v "${f}" "${dst}"
done
