#!/bin/bash

set -e
set -u
set -o pipefail

order=(
    core/coreutils
    core/filesystem
    core/system
    core/gettext
    core/glibtool
    core/autoconf
    core/automake
    core/pkg-config
    core/bash
    core/xz
    core/openssl
    core/libarchive
    core/asciidoc
    core/fakeroot
    core/readline
    core/libgpg-error
    core/libgcrypt
    core/libassuan
    core/libksba
    core/pth
    core/npth
    core/pinentry
    core/gnupg
    core/pacman
    core/pacman-mirrorlist
    core/binutils
    extra/libxml2
    extra/go
    extra/libffi
    extra/swig
    extra/llvm
    extra/http-parser
    extra/icu
    extra/libuv
    extra/nodejs
    extra/npm
    extra/gperf
    extra/unibilium
    extra/lua
    extra/lua51
    extra/lua52
    extra/luajit
    extra/xvidcore
    extra/nasm
    extra/libx264
    extra/lame
)

unordered=($(cat))
ordered=()

if [[ ${#unordered[@]} -eq 0 ]]; then
    exit 0
fi

for a in "${order[@]}"; do
    for b in "${unordered[@]}"; do
        if [[ "${a}" == "${b}" ]]; then
            ordered[${#ordered[@]}]="${a}"
        fi
    done
done

for a in "${unordered[@]}"; do
    present=""
    if [[ ${#ordered[@]} -ne 0 ]]; then
        for b in "${ordered[@]}"; do
            if [[ "${a}" == "${b}" ]]; then
                present="1"
            fi
        done
    fi
    if [[ -z "${present}" ]]; then
        ordered[${#ordered[@]}]="${a}"
    fi
done

for a in "${ordered[@]}"; do
    echo "${a}"
done
