#!/bin/bash

set -e
set -u
set -o pipefail

tgt="${*:$#}"
pkg=("${@:1:$# - 1}")
srv="${tgt%%:*}"
dst="${tgt##*:}"

if [[ "${#pkg[@]}" -eq 0 ]]; then
    exit
fi

for p in "${pkg[@]}"; do
    repo="${p%%/*}"
    path="${p%/*}"
    db="${path}/${repo}.db.tar.gz"
    p="${p##*/}"
    p="$(echo $p | sed -e 's#-[^-]*-[^-]*-[^-]*$##')"
    ssh "${srv}" repo-remove "${dst}${dst:+/}${db}" "${p}"
done
