#!/bin/bash

set -e
set -u
set -o pipefail

tgt="${*:$#}"
src=("${@:1:$# - 1}")
srv="${tgt%%:*}"
dst="${tgt##*:}"

if [[ ! -f "${src[0]}" ]]; then
    exit
fi

rsync -rtOz -v "${src[@]}" "${tgt}"
for repo in "${src[@]}"; do
    pushd "${repo}/.." > /dev/null
    repo="${repo##*/}"
    for path in "${repo}"/*/*; do
        db="${path}/${repo}.db.tar.gz"
        packages=("${path}"/*.pkg.tar.gz)
        packages=("${packages[@]/#/${dst}${dst:+/}}")
        echo "*** ${db}"
        ssh "${srv}" repo-add "${dst}${dst:+/}${db}" "${packages[@]}"
    done
    popd > /dev/null
done
