version: 2

jobs:
    build:
        macos:
            xcode: "8.3.3"
        steps:
            - run:
                name: Pristine macOS
                command: |
                    sudo mkdir -p /opt
                    sudo rm -rf /usr/local/*
                    sudo rm -rf /opt/*
                    echo > ~/.bashrc
                    echo > ~/.bash_profile
                    echo > ~/.circlerc
            - run:
                name: Setup Arch
                command: |
                    curl -o /tmp/snapshot.tar.gz https://download.archmac.org/snapshots/archmac-snapshot.tar.gz
                    sudo tar -C / -xvpzf /tmp/snapshot.tar.gz
                    sudo sed -i~ -e 's/^#Server =/Server =/' /opt/arch/etc/pacman.d/mirrorlist
                    echo 'export PATH="/opt/arch/bin:/opt/arch/sbin:$PATH"' >> ~/.archrc
                    echo 'source ~/.archrc' | tee -a ~/.bashrc ~/.bash_profile > /dev/null
            - run:
                name: Update Arch
                command: |
                    source ~/.archrc
                    sudo pacman --sync --refresh --noprogressbar
                    sudo pacman --sync --sysupgrade --noprogressbar --noconfirm --downloadonly
                    sudo pacman --sync --sysupgrade --noprogressbar --noconfirm
                    sudo pacman --sync --noprogressbar --noconfirm base-devel
            - checkout
            - run:
                name: Build packages
                command: |
                    source ~/.archrc
                    .support/changes -u origin/master "${CIRCLE_SHA1}" | .support/order
                    .support/build $(.support/changes -u origin/master "${CIRCLE_SHA1}" | .support/order)
            - run:
                name: Copy packages
                command: |
                    source ~/.archrc
                    .support/copy $(.support/built) /tmp/workspace/packages
            - run:
                name: Mark package deletions
                command: |
                    source ~/.archrc
                    .support/changes -d origin/master "${CIRCLE_SHA1}" | .support/order
                    .support/deleted $(.support/changes -b -d origin/master "${CIRCLE_SHA1}") | tee /tmp/workspace/deletions
            - persist_to_workspace:
                root: /tmp/workspace
                paths:
                    - packages
                    - deletions
            - store_artifacts:
                path: /tmp/workspace/packages
    push:
        macos:
            xcode: "8.3.3"
        steps:
            - run:
                name: Pristine macOS
                command: |
                    sudo mkdir -p /opt
                    sudo rm -rf /usr/local/*
                    sudo rm -rf /opt/*
                    echo > ~/.bashrc
                    echo > ~/.bash_profile
                    echo > ~/.circlerc
            - checkout
            - attach_workspace:
                at: /tmp/workspace
            - run:
                name: Remove packages
                command: |
                    cd /tmp/workspace; "${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"/.support/s3put deletions archmac.fra1.digitaloceanspaces.com/builds/${CIRCLE_SHA1}/
            - run:
                name: Upload packages
                command: |
                    cd /tmp/workspace; "${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"/.support/s3put packages archmac.fra1.digitaloceanspaces.com/builds/${CIRCLE_SHA1}/

workflows:
    version: 2
    build:
        jobs:
            - build
            - push:
                requires:
                    - build
