version: 2

jobs:
    build:
        macos:
            xcode: "8.3.3"
        steps:
            - run:
                name: Pristine macOS
                command: |
                    sudo mkdir -p /opt
                    sudo rm -rf /usr/local/*
                    sudo rm -rf /opt/*
                    echo > ~/.bashrc
                    echo > ~/.bash_profile
                    echo > ~/.circlerc
            - run:
                name: Setup Arch
                command: |
                    curl -o /tmp/snapshot.tar.gz https://download.archmac.org/snapshots/archmac-snapshot.tar.gz
                    sudo tar -C / -xvpzf /tmp/snapshot.tar.gz
                    sudo sed -i~ -e 's/^#Server =/Server =/' /opt/arch/etc/pacman.d/mirrorlist
                    echo 'export PATH="/opt/arch/bin:/opt/arch/sbin:$PATH"' >> ~/.archrc
                    echo 'source ~/.archrc' | tee -a ~/.bashrc ~/.bash_profile > /dev/null
            - run:
                name: Update Arch
                command: |
                    source ~/.archrc
                    sudo pacman --sync --refresh --noprogressbar
                    sudo pacman --sync --sysupgrade --noprogressbar --noconfirm --downloadonly
                    sudo pacman --sync --sysupgrade --noprogressbar --noconfirm
                    sudo pacman --sync --noprogressbar --noconfirm base-devel
            - checkout
            - run:
                name: Build packages
                command: |
                    source ~/.archrc
                    .support/changes -u origin/master "${CIRCLE_SHA1}" | .support/order
                    .support/build $(.support/changes -u origin/master "${CIRCLE_SHA1}" | .support/order)
            - run:
                name: Copy packages
                command: |
                    source ~/.archrc
                    .support/copy $(.support/built) /tmp/workspace/packages
            - run:
                name: Mark package deletions
                command: |
                    source ~/.archrc
                    .support/changes -d origin/master "${CIRCLE_SHA1}" | .support/order
                    .support/deleted $(.support/changes -b -d origin/master "${CIRCLE_SHA1}") | tee /tmp/workspace/deletions
            - persist_to_workspace:
                root: /tmp/workspace
                paths:
                    - packages
                    - deletions
            - store_artifacts:
                path: /tmp/workspace/packages
    push:
        macos:
            xcode: "8.3.3"
        steps:
            - run:
                name: Pristine macOS
                command: |
                    sudo mkdir -p /opt
                    sudo rm -rf /usr/local/*
                    sudo rm -rf /opt/*
                    echo > ~/.bashrc
                    echo > ~/.bash_profile
                    echo > ~/.circlerc
            - checkout
            - attach_workspace:
                at: /tmp/workspace
            - add_ssh_keys:
                fingerprints:
                    - "89:be:32:e8:7e:b8:7b:e5:2a:c0:0f:d9:b7:78:76:d1"
            - run:
                name: Add remote ssh host
                command: |
                    cat >> ~/.ssh/known_hosts <<'EOF'
                    download.archmac.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCRDDd1wxRN9dSZ9VS4P2UVsQE+IpO3jj3FUtOQcFVtzQnBRBucTXZ99/8masCy6gxAZ7JdY1+JxZKuiVmXuT6fP7JHedRUBuyR3hHtLFM1y6GRaJoJV0SBhgD8T4YT/yVk7TK/TIeUMon39XSdPcwD1aJMGCUB2NUClnXVfzElSoc+sabJepdH8ZfNeS+ChZpU/JvAjRKkjMlqW1GAsO5KmNPe9kgmM81weklYI36NImVaauBqgHZLVEbThSpKx59OLATXUFRuhBMAchcvbXGSUqfx3CiKtt3CSscsMAv40q648ohBVdGZ0XEdbNa6HSNKDTzmsllCFi6oSIWNGGMP
                    EOF
            - run:
                name: Remove packages
                command: |
                    .support/prune $(cat /tmp/workspace/deletions) upload@download.archmac.org:packages
            - run:
                name: Upload packages
                command: |
                    .support/push /tmp/workspace/packages/* upload@download.archmac.org:packages

workflows:
    version: 2
    build:
        jobs:
            - build
            - push:
                requires:
                    - build
                filters:
                  branches:
                    only: master
